### ISSUE TITLE
create loot functions

### ISSUE THREAD

**Issue by krbz999** [krbz999/simple-loot-list#3]
- [x] a `deleteAll` method to clear the list.
- [x] a way to target a token (or assigned character) and add the list of items to that actor.
- [ ] create Item Pile if `Item Piles` is active. (possibly with WG integration as well)
- [ ] way to turn loot actor into an item pile.

**Comment by GamerFlix** [comment]
It would be neat if the ItemPile creation call would return the created pile so it can be passed to the itempile API should further changes be wanted.

**Comment by krbz999** [comment]
Closing this and leaving all module integrations for future PRs.
